test.1.a = multiple_gonotrophic_cycles_singles_dispersal_not_deployed_sd_scaled(intervention.trait.mean.i = 0,
                                                                              intervention.trait.mean.j = 0,
                                                                              refugia.trait.mean.i = 0,
                                                                              refugia.trait.mean.j = 0,
                                                                              z.sd.intercept = 24,
                                                                              z.sd.coefficient = 0.4,
                                                                              female.exposure = 0.7,
                                                                              exposure.scaling.factor = 10,
                                                                              coverage = 1,
                                                                              dispersal.rate = 0,
                                                                              male.differential.intervention.i = 0,
                                                                              male.differential.intervention.j = 0,
                                                                              male.differential.refugia.i = 0,
                                                                              male.differential.refugia.j = 0,
                                                                              female.fitness.cost.i = 0,
                                                                              female.fitness.cost.j = 0,
                                                                              heritability.i = 1,
                                                                              heritability.j = 1,
                                                                              n.cycles = 10,
                                                                              half.population.bioassay.survival.resistance = 900,
                                                                              michaelis.menten.slope = 1,
                                                                              maximum.bioassay.survival.proportion = 1,
                                                                              regression.coefficient = 0.5,
                                                                              regression.intercept = 0.15,
                                                                              current.insecticide.efficacy.j = 1,
                                                                              cross.selection.j.i = 0.5,
                                                                              vector.length = 10000)


test.1.b = multiple_gonotrophic_cycles_singles_dispersal_not_deployed_sd_scaled(intervention.trait.mean.i = 0,
                                                                                intervention.trait.mean.j = 0,
                                                                                refugia.trait.mean.i = 0,
                                                                                refugia.trait.mean.j = 0,
                                                                                z.sd.intercept = 24,
                                                                                z.sd.coefficient = 0.4,
                                                                                female.exposure = 0.7,
                                                                                exposure.scaling.factor = 10,
                                                                                coverage = 0.7,
                                                                                dispersal.rate = 0.3,
                                                                                male.differential.intervention.i = 0,
                                                                                male.differential.intervention.j = 0,
                                                                                male.differential.refugia.i = 0,
                                                                                male.differential.refugia.j = 0,
                                                                                female.fitness.cost.i = 0,
                                                                                female.fitness.cost.j = 0,
                                                                                heritability.i = 1,
                                                                                heritability.j = 1,
                                                                                n.cycles = 10,
                                                                                half.population.bioassay.survival.resistance = 900,
                                                                                michaelis.menten.slope = 1,
                                                                                maximum.bioassay.survival.proportion = 1,
                                                                                regression.coefficient = 0.5,
                                                                                regression.intercept = 0.15,
                                                                                current.insecticide.efficacy.j = 1,
                                                                                cross.selection.j.i = 0.5,
                                                                                vector.length = 10000)

test_that("cross selection occurs", {
  expect_gt(test.1.a[[1]], 0)
  expect_gt(test.1.b[[1]], 0)
  expect_gt(test.1.b[[2]], 0)
})

test.2.a = multiple_gonotrophic_cycles_singles_dispersal_not_deployed_sd_scaled(intervention.trait.mean.i = 0,
                                                                                intervention.trait.mean.j = 0,
                                                                                refugia.trait.mean.i = 0,
                                                                                refugia.trait.mean.j = 0,
                                                                                z.sd.intercept = 24,
                                                                                z.sd.coefficient = 0.4,
                                                                                female.exposure = 0.7,
                                                                                exposure.scaling.factor = 10,
                                                                                coverage = 1,
                                                                                dispersal.rate = 0,
                                                                                male.differential.intervention.i = -1000,
                                                                                male.differential.intervention.j = 0,
                                                                                male.differential.refugia.i = -1000,
                                                                                male.differential.refugia.j = 0,
                                                                                female.fitness.cost.i = 1,
                                                                                female.fitness.cost.j = 0,
                                                                                heritability.i = 1,
                                                                                heritability.j = 1,
                                                                                n.cycles = 10,
                                                                                half.population.bioassay.survival.resistance = 900,
                                                                                michaelis.menten.slope = 1,
                                                                                maximum.bioassay.survival.proportion = 1,
                                                                                regression.coefficient = 0.5,
                                                                                regression.intercept = 0.15,
                                                                                current.insecticide.efficacy.j = 1,
                                                                                cross.selection.j.i = 0,
                                                                                vector.length = 10000)


test.2.b = multiple_gonotrophic_cycles_singles_dispersal_not_deployed_sd_scaled(intervention.trait.mean.i = 0,
                                                                                intervention.trait.mean.j = 0,
                                                                                refugia.trait.mean.i = 0,
                                                                                refugia.trait.mean.j = 0,
                                                                                z.sd.intercept = 24,
                                                                                z.sd.coefficient = 0.4,
                                                                                female.exposure = 0.7,
                                                                                exposure.scaling.factor = 10,
                                                                                coverage = 0.7,
                                                                                dispersal.rate = 0.3,
                                                                                male.differential.intervention.i = -1000,
                                                                                male.differential.intervention.j = 0,
                                                                                male.differential.refugia.i = -1000,
                                                                                male.differential.refugia.j = 0,
                                                                                female.fitness.cost.i = 1,
                                                                                female.fitness.cost.j = 0,
                                                                                heritability.i = 1,
                                                                                heritability.j = 1,
                                                                                n.cycles = 10,
                                                                                half.population.bioassay.survival.resistance = 900,
                                                                                michaelis.menten.slope = 1,
                                                                                maximum.bioassay.survival.proportion = 1,
                                                                                regression.coefficient = 0.5,
                                                                                regression.intercept = 0.15,
                                                                                current.insecticide.efficacy.j = 1,
                                                                                cross.selection.j.i = 0,
                                                                                vector.length = 10000)

test_that("resistance cannot fall below zero", {
  expect_equal(test.2.a[[1]], 0)
  expect_equal(test.2.b[[1]], 0)
  expect_equal(test.2.b[[1]], 0)
})
