fixed.sd.sim = run_simulation_advanced(irm.deployment.strategy = "singles", #singles, mixtures, micromosaics, combinations
                                       irm.switch.strategy = "sequence", #"rotation", "sequence", "insecticide.1"
                                       number.of.insecticides = 1,
                                       sd.scaled = FALSE, ##TRUE or FALSE
                                       exposure.scaling.factor = 10,
                                       female.fitness.cost = 0,
                                       male.fitness.cost = 0,
                                       female.exposure = 0.8,
                                       male.exposure = 0.7,
                                       heritability = 0.3,
                                       dispersal.rate = 0.2,
                                       coverage = 0.8,
                                       standard.deviation = 50,
                                       vector.length = 1000,
                                       maximum.bioassay.survival.proportion = 1,
                                       michaelis.menten.slope = 1,
                                       regression.coefficient = 0.48,
                                       regression.intercept = 0.15,
                                       maximum.generations = 500,
                                       half.population.bioassay.survival.resistance = 900,
                                       withdrawal.threshold.value = 1,
                                       return.threshold.value = 0.05,
                                       deployment.frequency = 10,
                                       maximum.resistance.value = 25000,
                                       starting.refugia.resistance.score = 0,
                                       starting.intervention.resistance.score = 0,
                                       applied.insecticide.dose = 1,
                                       recommended.insecticide.dose = 1,
                                       threshold.generations = 15,
                                       base.efficacy.decay.rate = 0.015,
                                       rapid.decay.rate = 0.08,
                                       deployment.interval.llin = 30,
                                       deployment.interval.irs = 10,
                                       probability.only.i.male = 0.7,
                                       probability.only.j.male = 0.2,
                                       probability.both.i.j.male = 0.1,
                                       probability.only.i.female = 0.4,
                                       probability.only.j.female = 0.2,
                                       probability.both.i.j.female = 0.4,
                                       n.cycles = 1,
                                       intervention.coverage.1 = 0.5,
                                       intervention.coverage.2 = 0.5,
                                       intervention.coverage.1.2 = 0,
                                       z.sd.intercept = 18,
                                       z.sd.coefficient = 0.4,
                                       mixture.strategy = "pyrethroid.plus",
                                       llin.insecticides = NA,
                                       irs.insecticides = NA,
                                       min.cross.selection = 0,
                                       max.cross.selection = 0,
                                       gonotrophic.cycle.length = 1,
                                       natural.daily.survival = 1)



scaled.sd.sim = run_simulation_advanced(irm.deployment.strategy = "singles", #singles, mixtures, micromosaics, combinations
                                       irm.switch.strategy = "sequence", #"rotation", "sequence", "insecticide.1"
                                       number.of.insecticides = 1,
                                       sd.scaled = TRUE, ##TRUE or FALSE
                                       exposure.scaling.factor = 10,
                                       female.fitness.cost = 0,
                                       male.fitness.cost = 0,
                                       female.exposure = 0.8,
                                       male.exposure = 0.7,
                                       heritability = 0.3,
                                       dispersal.rate = 0.2,
                                       coverage = 0.8,
                                       standard.deviation = 50,
                                       vector.length = 1000,
                                       maximum.bioassay.survival.proportion = 1,
                                       michaelis.menten.slope = 1,
                                       regression.coefficient = 0.48,
                                       regression.intercept = 0.15,
                                       maximum.generations = 500,
                                       half.population.bioassay.survival.resistance = 900,
                                       withdrawal.threshold.value = 1,
                                       return.threshold.value = 0.05,
                                       deployment.frequency = 10,
                                       maximum.resistance.value = 25000,
                                       starting.refugia.resistance.score = 0,
                                       starting.intervention.resistance.score = 0,
                                       applied.insecticide.dose = 1,
                                       recommended.insecticide.dose = 1,
                                       threshold.generations = 15,
                                       base.efficacy.decay.rate = 0.015,
                                       rapid.decay.rate = 0.08,
                                       deployment.interval.llin = 30,
                                       deployment.interval.irs = 10,
                                       probability.only.i.male = 0.7,
                                       probability.only.j.male = 0.2,
                                       probability.both.i.j.male = 0.1,
                                       probability.only.i.female = 0.4,
                                       probability.only.j.female = 0.2,
                                       probability.both.i.j.female = 0.4,
                                       n.cycles = 1,
                                       intervention.coverage.1 = 0.5,
                                       intervention.coverage.2 = 0.5,
                                       intervention.coverage.1.2 = 0,
                                       z.sd.intercept = 18,
                                       z.sd.coefficient = 0.4,
                                       mixture.strategy = "pyrethroid.plus",
                                       llin.insecticides = NA,
                                       irs.insecticides = NA,
                                       min.cross.selection = 0,
                                       max.cross.selection = 0,
                                       gonotrophic.cycle.length = 1,
                                       natural.daily.survival = 1)




ggplot(subset(fixed.sd.sim, site == "intervention"), aes(x=time.in.generations,
                                                         y =bioassay.survival*100))+
  geom_line(colour = "red", size = 2)+
  geom_line(data=subset(scaled.sd.sim, site == "intervention"), aes(x=time.in.generations,
                                                                  y=bioassay.survival*100),
            colour = "blue", size = 2)+
  xlab("Time in Generations")+
  ylab("Bioassay Survival (%)")+
  ggtitle("polysmooth")+
  theme_bw()
