tracked_insecticide_is_deployed_in_mixture = function(deployed.mixture,
                                              current.generation,
                                              insecticide,
                                              sim.array){

insecticide.j = get_other_insecticide_mixture(deployed.mixture,
                              generation = current.generation,
                              insecticide = insecticide,
                              sim.array = sim.arrray)


efficacy.tracked.insecticide = get_other_mixture_part_decay_information(tracked.insecticide = insecticide.j,
                                                                        deployed.mixture = deployed.mixture,
                                                                        generation = generation)

efficacy.insecticide.j = get_other_mixture_part_decay_information(tracked.insecticide = insecticide,
                                                                    deployed.mixture = deployed.mixture,
                                                                    generation = generation)

tracked.resistance =   multiple_gonotrophic_cycles_mixture_dispersal(intervention.trait.mean.i = sim.array['intervention', insecticide, generation-1],
                                                                     intervention.trait.mean.j = sim.array['intervention', insecticide.j, generation-1],
                                                                     refugia.trait.mean.i = sim.array['refugia', insecticide, generation-1],
                                                                     refugia.trait.mean.j = sim.array['refugia', insecticide.j, generation-1],
                                                                     standard.deviation = standard.deviation,
                                                                     vector.length = vector.length,
                                                                     female.exposure = female.exposure,
                                                                     exposure.scaling.factor = exposure.scaling.factor,
                                                                     coverage = coverage,
                                                                     dispersal.rate = dispersal.rate,
                                                                     male.differential.intervention.i = wrapper_calculate_male_insecticide_fitness_selection_differential_mixtures(male.trait.mean = sim.array['intervention', insecticide, generation-1],
                                                                                                                                                                                   female.insecticide.exposure = female.exposure,
                                                                                                                                                                                   male.insecticide.exposure = male.exposure,
                                                                                                                                                                                   standard.deviation = standard.deviation,
                                                                                                                                                                                   male.fitness.cost = insecticide.parameters.df$male.fitness.cost[insecticide],
                                                                                                                                                                                   vector.length = vector.length,
                                                                                                                                                                                   maximum.bioassay.survival.proportion = maximum.bioassay.survival.proportion,
                                                                                                                                                                                   michaelis.menten.slope = michaelis.menten.slope,
                                                                                                                                                                                   half.population.bioassay.survival.resistance = half.population.bioassay.survival.resistance,
                                                                                                                                                                                   regression.coefficient = regression.coefficient,
                                                                                                                                                                                   regression.intercept = regression.intercept,
                                                                                                                                                                                   current.insecticide.efficacy = efficacy.tracked.insecticide,
                                                                                                                                                                                   exposure.scaling.factor = exposure.scaling.factor,
                                                                                                                                                                                   survival.to.other.insecticide = convert_bioassay_survival_to_field_survival(bioassay.survival = convert_resistance_score_to_bioassay_survival(maximum.bioassay.survival.proportion = maximum.bioassay.survival.proportion,
                                                                                                                                                                                                                                                                                                                                 trait.mean = sim.array['intervention', insecticide.j, generation-1],
                                                                                                                                                                                                                                                                                                                                 michaelis.menten.slope = michaelis.menten.slope,
                                                                                                                                                                                                                                                                                                                                 half.population.bioassay.survival.resistance = half.population.bioassay.survival.resistance),
                                                                                                                                                                                                                                                               regression.coefficient = regression.coefficient,
                                                                                                                                                                                                                                                               regression.intercept = regression.intercept,
                                                                                                                                                                                                                                                               current.insecticide.efficacy = efficacy.insecticide.j)),
                                                                     male.differential.intervention.j =  wrapper_calculate_male_insecticide_fitness_selection_differential_mixtures(male.trait.mean = sim.array['intervention', insecticide.j, generation-1],
                                                                                                                                                                                    female.insecticide.exposure = female.exposure,
                                                                                                                                                                                    male.insecticide.exposure = male.exposure,
                                                                                                                                                                                    standard.deviation = standard.deviation,
                                                                                                                                                                                    male.fitness.cost = insecticide.parameters.df$male.fitness.cost[insecticide.j],
                                                                                                                                                                                    vector.length = vector.length,
                                                                                                                                                                                    maximum.bioassay.survival.proportion = maximum.bioassay.survival.proportion,
                                                                                                                                                                                    michaelis.menten.slope = michaelis.menten.slope,
                                                                                                                                                                                    half.population.bioassay.survival.resistance = half.population.bioassay.survival.resistance,
                                                                                                                                                                                    regression.coefficient = regression.coefficient,
                                                                                                                                                                                    regression.intercept = regression.intercept,
                                                                                                                                                                                    current.insecticide.efficacy = efficacy.insecticide.j,
                                                                                                                                                                                    exposure.scaling.factor = exposure.scaling.factor,
                                                                                                                                                                                    survival.to.other.insecticide = convert_bioassay_survival_to_field_survival(bioassay.survival = convert_resistance_score_to_bioassay_survival(maximum.bioassay.survival.proportion = maximum.bioassay.survival.proportion,
                                                                                                                                                                                                                                                                                                                                  trait.mean = sim.array['intervention', insecticide, generation-1],
                                                                                                                                                                                                                                                                                                                                  michaelis.menten.slope = michaelis.menten.slope,
                                                                                                                                                                                                                                                                                                                                  half.population.bioassay.survival.resistance = half.population.bioassay.survival.resistance),
                                                                                                                                                                                                                                                                regression.coefficient = regression.coefficient,
                                                                                                                                                                                                                                                                regression.intercept = regression.intercept,
                                                                                                                                                                                                                                                                current.insecticide.efficacy = efficacy.tracked.insecticide)),
                                                                     male.differential.refugia.i = wrapper_male_fitness_selection_differential(male.trait.mean = sim.array['refugia', insecticide, generation-1],
                                                                                                                                               male.fitness.cost = insecticide.parameters.df$male.fitness.cost[insecticide]),
                                                                     male.differential.refugia.j = wrapper_male_fitness_selection_differential(male.trait.mean = sim.array['refugia', insecticide.j, generation-1],
                                                                                                                                               male.fitness.cost = insecticide.parameters.df$male.fitness.cost[insecticide.j]),
                                                                     female.fitness.cost.i = insecticide.parameters.df$female.fitness.cost[insecticide],
                                                                     female.fitness.cost.j = insecticide.parameters.df$female.fitness.cost[insecticide.j],
                                                                     heritability.i = insecticide.parameters.df$heritability[insecticide],
                                                                     heritability.j = insecticide.parameters.df$heritability[insecticide.j],
                                                                     n.cycles = n.cycles,
                                                                     half.population.bioassay.survival.resistance = half.population.bioassay.survival.resistance,
                                                                     michaelis.menten.slope = michaelis.menten.slope,
                                                                     maximum.bioassay.survival.proportion = maximum.bioassay.survival.proportion,
                                                                     regression.coefficient = regression.coefficient,
                                                                     regression.intercept = regression.intercept,
                                                                     current.insecticide.efficacy.i = efficacy.tracked.insecticide,
                                                                     current.insecticide.efficacy.j = efficacy.insecticide.j)

sim.array['intervention', insecticide, generation] = tracked.resistance[[1]]
sim.array['refugia', insecticide, generation] = tracked.resistance[[2]]


}
